-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 22:12:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `grad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grad` (
  `idgrad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgrad`),
  UNIQUE INDEX `idgrad_UNIQUE` (`idgrad` ASC) VISIBLE,
  UNIQUE INDEX `naziv_UNIQUE` (`naziv` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pol` (
  `idpol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pol` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`idpol`),
  UNIQUE INDEX `idpol_UNIQUE` (`idpol` ASC) VISIBLE,
  UNIQUE INDEX `pol_UNIQUE` (`pol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipKorisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipKorisnika` (
  `idtipKorisnika` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idtipKorisnika`),
  UNIQUE INDEX `tip_UNIQUE` (`tip` ASC) VISIBLE,
  UNIQUE INDEX `idtipKorisnika_UNIQUE` (`idtipKorisnika` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `korisnik` (
  `idKorisnik` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `licnoIme` VARCHAR(64) NULL,
  `prikaziLicnoIme` BIT NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `tipKorisnika_idtipKorisnika` INT UNSIGNED NOT NULL,
  `grad_idgrad` INT UNSIGNED NULL,
  `pol_idpol` INT UNSIGNED NOT NULL,
  `slika` BLOB NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idKorisnik`),
  UNIQUE INDEX `id_UNIQUE` (`idKorisnik` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_korisnik_grad1_idx` (`grad_idgrad` ASC) VISIBLE,
  INDEX `fk_korisnik_pol1_idx` (`pol_idpol` ASC) VISIBLE,
  INDEX `fk_korisnik_tipKorisnika1_idx` (`tipKorisnika_idtipKorisnika` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_grad1`
    FOREIGN KEY (`grad_idgrad`)
    REFERENCES `grad` (`idgrad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_pol1`
    FOREIGN KEY (`pol_idpol`)
    REFERENCES `pol` (`idpol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_tipKorisnika1`
    FOREIGN KEY (`tipKorisnika_idtipKorisnika`)
    REFERENCES `tipKorisnika` (`idtipKorisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `kategorijaPitanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kategorijaPitanja` (
  `idkategorijaPitanja` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kategorija` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkategorijaPitanja`),
  UNIQUE INDEX `idkategorijaPitanja_UNIQUE` (`idkategorijaPitanja` ASC) VISIBLE,
  UNIQUE INDEX `kategorija_UNIQUE` (`kategorija` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pitanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pitanje` (
  `idPitanje` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `korisnik_idKorisnik_postavio` INT UNSIGNED NOT NULL,
  `kategorijaPitanja_idkategorija` INT UNSIGNED NULL,
  `naslovPitanja` VARCHAR(128) NOT NULL,
  `tekstPitanja` TEXT NOT NULL,
  `postavljenoAnonimno` BIT NOT NULL COMMENT '\n',
  `moguSviDaOdgovore` BIT NOT NULL,
  PRIMARY KEY (`idPitanje`),
  INDEX `fk_pitanje_korisnik_idx` (`korisnik_idKorisnik_postavio` ASC) VISIBLE,
  INDEX `fk_pitanje_kategorijaPitanja1_idx` (`kategorijaPitanja_idkategorija` ASC) VISIBLE,
  CONSTRAINT `fk_pitanje_korisnik`
    FOREIGN KEY (`korisnik_idKorisnik_postavio`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pitanje_kategorijaPitanja1`
    FOREIGN KEY (`kategorijaPitanja_idkategorija`)
    REFERENCES `kategorijaPitanja` (`idkategorijaPitanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `korisnik_ocenio_pitanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `korisnik_ocenio_pitanje` (
  `korisnik_idKorisnik` INT UNSIGNED NOT NULL,
  `pitanje_idPitanje` INT UNSIGNED NOT NULL,
  `ocena` BIT NOT NULL COMMENT '1 na gore, 0 na dole',
  PRIMARY KEY (`korisnik_idKorisnik`, `pitanje_idPitanje`),
  INDEX `fk_korisnik_has_pitanje_pitanje1_idx` USING BTREE (`pitanje_idPitanje`) COMMENT 'Bitan indeks, jer nam on treba za dobijanje svih ocena nekog pitanja.' VISIBLE,
  INDEX `fk_korisnik_has_pitanje_korisnik1_idx` (`korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_has_pitanje_korisnik1`
    FOREIGN KEY (`korisnik_idKorisnik`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_has_pitanje_pitanje1`
    FOREIGN KEY (`pitanje_idPitanje`)
    REFERENCES `pitanje` (`idPitanje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION) PARTITION BY HASH(pitanje_idPitanje) PARTITIONS 1 ;


-- -----------------------------------------------------
-- Table `odgovor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odgovor` (
  `idodgovor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pitanje_idPitanje` INT UNSIGNED NOT NULL,
  `korisnik_idKorisnik_odgovorio` INT UNSIGNED NOT NULL,
  `tekstOdgovora` TEXT NOT NULL,
  `odgovorenoAnonimno` BIT NOT NULL,
  PRIMARY KEY (`idodgovor`),
  UNIQUE INDEX `idodgovor_UNIQUE` (`idodgovor` ASC) VISIBLE,
  INDEX `fk_odgovor_pitanje1_idx` (`pitanje_idPitanje` ASC) VISIBLE,
  INDEX `fk_odgovor_korisnik1_idx` (`korisnik_idKorisnik_odgovorio` ASC) VISIBLE,
  CONSTRAINT `fk_odgovor_pitanje1`
    FOREIGN KEY (`pitanje_idPitanje`)
    REFERENCES `pitanje` (`idPitanje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_odgovor_korisnik1`
    FOREIGN KEY (`korisnik_idKorisnik_odgovorio`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seansa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seansa` (
  `idseansa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `korisnik_idKorisnik_organizator` INT UNSIGNED NOT NULL,
  `nazivSeanse` VARCHAR(80) NOT NULL,
  `opisSeanse` TEXT NOT NULL,
  `maxBrojPrijavljenih` TINYINT NOT NULL,
  `trenutanBrojPrijavljenih` TINYINT GENERATED ALWAYS AS (SELECT COUNT(*) FROM korisnik_prijavljen_na_seansu kpns, seansa s WHERE s.idseansa = kpns.seansa_idseansa) VIRTUAL,
  `datumPocetka` DATE NOT NULL,
  `vremePocetka` TIME NOT NULL,
  `zoomLink` VARCHAR(255) NULL,
  PRIMARY KEY (`idseansa`),
  UNIQUE INDEX `idseansa_UNIQUE` (`idseansa` ASC) VISIBLE,
  INDEX `fk_seansa_korisnik1_idx` (`korisnik_idKorisnik_organizator` ASC) VISIBLE,
  CONSTRAINT `fk_seansa_korisnik1`
    FOREIGN KEY (`korisnik_idKorisnik_organizator`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `korisnik_prijavljen_na_seansu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `korisnik_prijavljen_na_seansu` (
  `korisnik_idKorisnik` INT UNSIGNED NOT NULL,
  `seansa_idseansa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`korisnik_idKorisnik`, `seansa_idseansa`),
  INDEX `fk_korisnik_prijavljen_na_seansu_seansa1_idx` (`seansa_idseansa` ASC) VISIBLE,
  INDEX `fk_korisnik_prijavljen_na_seansu_korisnik1_idx` (`korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_prijavljen_na_seansu_korisnik1`
    FOREIGN KEY (`korisnik_idKorisnik`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_prijavljen_na_seansu_seansa1`
    FOREIGN KEY (`seansa_idseansa`)
    REFERENCES `seansa` (`idseansa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `preporucenaLiteratura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `preporucenaLiteratura` (
  `idpreporucenaLiteratura` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazivLiterature` VARCHAR(80) NOT NULL,
  `slikaLiterature` TINYBLOB NOT NULL,
  `opisLiterature` TINYTEXT NOT NULL,
  PRIMARY KEY (`idpreporucenaLiteratura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `korisnik_ocenio_odgovor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `korisnik_ocenio_odgovor` (
  `korisnik_idKorisnik` INT UNSIGNED NOT NULL,
  `odgovor_idodgovor` INT UNSIGNED NOT NULL,
  `ocena` BIT NOT NULL,
  PRIMARY KEY (`korisnik_idKorisnik`, `odgovor_idodgovor`),
  INDEX `fk_korisnik_ocenio_odgovor_odgovor1_idx` (`odgovor_idodgovor` ASC) VISIBLE,
  INDEX `fk_korisnik_ocenio_odgovor_korisnik1_idx` (`korisnik_idKorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_ocenio_odgovor_korisnik1`
    FOREIGN KEY (`korisnik_idKorisnik`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_ocenio_odgovor_odgovor1`
    FOREIGN KEY (`odgovor_idodgovor`)
    REFERENCES `odgovor` (`idodgovor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `korisnik_ocenio_psihologa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `korisnik_ocenio_psihologa` (
  `korisnik_idKorisnik_ocenio` INT UNSIGNED NOT NULL,
  `korisnik_idKorisnik_ocenjen` INT UNSIGNED NOT NULL COMMENT 'Ovde se moze naci samo id korisnika koji je psiholog. Pre izvrsenja ocenjivanja, vrsi se ova provera.',
  `ocena` BIT NOT NULL,
  PRIMARY KEY (`korisnik_idKorisnik_ocenio`, `korisnik_idKorisnik_ocenjen`),
  INDEX `fk_korisnik_has_korisnik_korisnik2_idx` (`korisnik_idKorisnik_ocenjen` ASC) VISIBLE,
  INDEX `fk_korisnik_has_korisnik_korisnik1_idx` (`korisnik_idKorisnik_ocenio` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_has_korisnik_korisnik1`
    FOREIGN KEY (`korisnik_idKorisnik_ocenio`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_has_korisnik_korisnik2`
    FOREIGN KEY (`korisnik_idKorisnik_ocenjen`)
    REFERENCES `korisnik` (`idKorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
